<<<<<<< HEAD
spring.application.name=Jaulas
server.port=8081


#conecta a la base de datos de jorge "MicroservicioJaulas"
spring.datasource.url=jdbc:postgresql://ep-dry-sunset-apyivmer.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ocdCD4nN5xUg
=======
#conecta a la base de datos de jorge "MicroservicioUsuariosyRoles"
spring.datasource.url=jdbc:postgresql://ep-polished-heart-ap4g3csi-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bsmY9PeGnw5a
>>>>>>> dcc3677d5fefc15a7f2ba898766061de85f14fb9

# Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
=======
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
>>>>>>> dcc3677d5fefc15a7f2ba898766061de85f14fb9

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html