spring.application.name=Jaulas
server.port=8081

# Conecta a la base de datos de jorge "MicroservicioUsuariosyRoles"
spring.datasource.url=jdbc:postgresql://ep-polished-heart-ap4g3csi-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bsmY9PeGnw5a

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Si existe la variable de entorno CRIADEROS_URL en Render, la usa. Si no, usa localhost.
criaderos.service.url=${CRIADEROS_URL:http://localhost:8080/api/v1/criaderos}